"""Fixes zettelkasten topics

Revision ID: 2754363f5726
Revises: 7e176eb6e9ce
Create Date: 2024-09-22 16:47:28.039863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2754363f5726'
down_revision = '7e176eb6e9ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zettel_topic_association', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zettel_topic_association', 'similarity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
