"""Adds received_at field to email model

Revision ID: 546d32e737fb
Revises: 9bdd676c404e
Create Date: 2024-10-13 11:11:27.172378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546d32e737fb'
down_revision = '9bdd676c404e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('received_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'received_at')
    # ### end Alembic commands ###
