"""Makes table names plural

Revision ID: 5e0a4e287952
Revises: f48f965a7f32
Create Date: 2024-09-04 22:16:20.042715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e0a4e287952'
down_revision = 'f48f965a7f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('zettel', 'zettels')
    op.rename_table('oauth_credential', 'oauth_credentials')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('zettels', 'zettel')
    op.rename_table('oauth_credentials', 'oauth_credential')
    # ### end Alembic commands ###
