"""Adds waking hours to user model

Revision ID: 6fd1bf219aa5
Revises: ef0a904261b2
Create Date: 2024-10-13 23:36:52.922139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd1bf219aa5'
down_revision = 'ef0a904261b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('hour_awake', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('hour_bedtime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hour_bedtime')
    op.drop_column('users', 'hour_awake')
    op.drop_constraint(None, 'emails', type_='foreignkey')
    # ### end Alembic commands ###
