"""Creates Zettelkasten topics

Revision ID: 7e176eb6e9ce
Revises: 5e0a4e287952
Create Date: 2024-09-10 21:18:27.409347

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '7e176eb6e9ce'
down_revision = '5e0a4e287952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zettelkasten_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('centroid_instructor_base_embedding', src.models.Vector(768), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zettel_topic_association',
    sa.Column('zettel_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['zettelkasten_topics.id'], ),
    sa.ForeignKeyConstraint(['zettel_id'], ['zettels.id'], ),
    sa.PrimaryKeyConstraint('zettel_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zettel_topic_association')
    op.drop_table('zettelkasten_topics')
    # ### end Alembic commands ###
