"""Adds is_processed to email mode

Revision ID: 85088065311a
Revises: f1ddba865151
Create Date: 2024-08-31 15:42:33.032722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85088065311a'
down_revision = 'f1ddba865151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'is_processed')
    # ### end Alembic commands ###
