"""Adds user_id to email model

Revision ID: 8de2c13d1dc4
Revises: 9570d595bb27
Create Date: 2024-10-13 14:45:42.512856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8de2c13d1dc4'
down_revision = '9570d595bb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'user_id')
    # ### end Alembic commands ###
