"""Create open_questions table

Revision ID: 8e7253929870
Revises: 2754363f5726
Create Date: 2024-10-11 00:10:04.144884

"""
from alembic import op
import sqlalchemy as sa
import src

# revision identifiers, used by Alembic.
revision = '8e7253929870'
down_revision = '2754363f5726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('open_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructor_base_embedding', src.models.Vector(768), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_open_question_embedding', 'open_questions', ['instructor_base_embedding'], unique=False, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_open_question_embedding', table_name='open_questions', postgresql_using='ivfflat')
    op.drop_table('open_questions')
    # ### end Alembic commands ###
