"""Changes Oauth user id to int

Revision ID: 901ec8670b4a
Revises: 71712c504f5c
Create Date: 2024-08-22 22:41:08.386931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901ec8670b4a'
down_revision = '71712c504f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth_credential', 'user_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('oauth_credential_user_id_key', 'oauth_credential', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('oauth_credential_user_id_key', 'oauth_credential', ['user_id'])
    op.alter_column('oauth_credential', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
