"""Changes parent_gmail_id to parent_message_id and adds message_id to email

Revision ID: aa5f186c81c6
Revises: 5b8d904af4bc
Create Date: 2024-10-23 12:17:15.319459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5f186c81c6'
down_revision = '5b8d904af4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('enqueued_messages', sa.Column('parent_message_id', sa.String(length=255), nullable=True))
    op.drop_column('enqueued_messages', 'parent_gmail_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enqueued_messages', sa.Column('parent_gmail_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('enqueued_messages', 'parent_message_id')
    op.drop_column('emails', 'message_id')
    # ### end Alembic commands ###
