"""Rename email table to create new email table

Revision ID: af58b6555500
Revises: 7010d4d64f15
Create Date: 2024-08-30 23:14:30.300297

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af58b6555500'
down_revision = '7010d4d64f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('emails', 'emails_old')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('emails_old', 'emails')
    # ### end Alembic commands ###
