"""Adds history_id to email

Revision ID: b36d609a3300
Revises: 1c997589a27c
Create Date: 2024-08-31 16:41:02.325078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36d609a3300'
down_revision = '1c997589a27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('history_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'history_id')
    # ### end Alembic commands ###
