"""removes user email signatures

Revision ID: e3d4786c12a1
Revises: aa5f186c81c6
Create Date: 2024-11-30 11:33:17.112086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d4786c12a1'
down_revision = 'aa5f186c81c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signatures_csv')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signatures_csv', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
