"""Removes EmailOld table

Revision ID: f8a559d359ec
Revises: e3d4786c12a1
Create Date: 2024-11-30 11:47:41.488186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8a559d359ec'
down_revision = 'e3d4786c12a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emails_old')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emails_old',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('recipients_csv', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('thread_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sender_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name='emails_sender_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='emails_pkey')
    )
    # ### end Alembic commands ###
